### Register User
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstname": "yassine",
  "lastname": "lambarki",
  "email": "developpeurk@gmail.com",
  "role": "ADMIN",
  "password": "1234"
}

> {% client.global.set("auth-token", response.body.access_token) %}

### Query the demo endpoint
GET http://localhost:8080/api/v1/demo-controller
Authorization: Bearer {{ auth-token }}